### ISSUE TITLE
Release download...?

### ISSUE THREAD

**Issue by Efreak** [sptallent/jolly_music#1]
It's it possible to provide a release? If the API key can be configurable in-app, it should be possible to be built with FDroid (if it doesn't meet FDroid inclusion criteria, or can still be hosted in a 3rd party fdroid repo like izzyondroid)

**Comment by sptallent** [comment]
It's released on google play if that's what you mean by a release. The API key can be configurable by the developer but it would be great to add a setting to allow users to add their own AcoustAPI key in app. I can consider releasing this on Fdroid but I don't think too many people are interested in this project so I'm working on other projects for now. 

https://play.google.com/store/apps/details?id=sage.musicplayer&hl=en_US&gl=US

Would it be better to add an APK or app bundle download to this repository?

**Comment by Efreak** [comment]
It's entirely possible to add an APK here, yes. I suggested FDroid primarily because they'll take care of building when you update. Izzyondroid will pull your GitHub releases, not build the app themselves, as long as the file is small. As for the app bundle, it's *probably* better to split it into individual apk files per architecture if that's easy to do, that way Obtainium or other app can be used to update automatically from GitHub (I have no idea what apps support bundles, including those I use myself 🤷).

**Comment by sptallent** [comment]
I've added a release:
https://github.com/sptallent/jolly-music-player/releases/tag/jolly-music-player
